//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.MNB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="MNB.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetInfoResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetInfo", ReplyAction="*")]
        WCF.MNB.GetInfoResponse GetInfo(WCF.MNB.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNB.GetInfoResponse> GetInfoAsync(WCF.MNB.GetInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetCurrentExchangeRatesResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrentExchangeRates", ReplyAction="*")]
        WCF.MNB.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(WCF.MNB.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrentExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNB.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(WCF.MNB.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since element name startDate from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetExchangeRates", ReplyAction="*")]
        WCF.MNB.GetExchangeRatesResponse GetExchangeRates(WCF.MNB.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNB.GetExchangeRatesResponse> GetExchangeRatesAsync(WCF.MNB.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since element name GetDateIntervalResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetDateInterval", ReplyAction="*")]
        WCF.MNB.GetDateIntervalResponse GetDateInterval(WCF.MNB.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetDateInterval", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNB.GetDateIntervalResponse> GetDateIntervalAsync(WCF.MNB.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since element name GetCurrenciesResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencies", ReplyAction="*")]
        WCF.MNB.GetCurrenciesResponse GetCurrencies(WCF.MNB.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNB.GetCurrenciesResponse> GetCurrenciesAsync(WCF.MNB.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since element name currencyNames from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencyUnits", ReplyAction="*")]
        WCF.MNB.GetCurrencyUnitsResponse GetCurrencyUnits(WCF.MNB.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencyUnits", ReplyAction="*")]
        System.Threading.Tasks.Task<WCF.MNB.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(WCF.MNB.GetCurrencyUnitsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfo", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetInfoRequestBody Body;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(WCF.MNB.GetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInfoRequestBody {
        
        public GetInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetInfoResponseBody Body;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(WCF.MNB.GetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoResult;
        
        public GetInfoResponseBody() {
        }
        
        public GetInfoResponseBody(string GetInfoResult) {
            this.GetInfoResult = GetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRates", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetCurrentExchangeRatesRequestBody Body;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(WCF.MNB.GetCurrentExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrentExchangeRatesRequestBody {
        
        public GetCurrentExchangeRatesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetCurrentExchangeRatesResponseBody Body;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(WCF.MNB.GetCurrentExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrentExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentExchangeRatesResult;
        
        public GetCurrentExchangeRatesResponseBody() {
        }
        
        public GetCurrentExchangeRatesResponseBody(string GetCurrentExchangeRatesResult) {
            this.GetCurrentExchangeRatesResult = GetCurrentExchangeRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRates", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetExchangeRatesRequestBody Body;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(WCF.MNB.GetExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetExchangeRatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyNames;
        
        public GetExchangeRatesRequestBody() {
        }
        
        public GetExchangeRatesRequestBody(string startDate, string endDate, string currencyNames) {
            this.startDate = startDate;
            this.endDate = endDate;
            this.currencyNames = currencyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetExchangeRatesResponseBody Body;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(WCF.MNB.GetExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesResult;
        
        public GetExchangeRatesResponseBody() {
        }
        
        public GetExchangeRatesResponseBody(string GetExchangeRatesResult) {
            this.GetExchangeRatesResult = GetExchangeRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateInterval", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetDateIntervalRequestBody Body;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(WCF.MNB.GetDateIntervalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDateIntervalRequestBody {
        
        public GetDateIntervalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetDateIntervalResponseBody Body;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(WCF.MNB.GetDateIntervalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetDateIntervalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDateIntervalResult;
        
        public GetDateIntervalResponseBody() {
        }
        
        public GetDateIntervalResponseBody(string GetDateIntervalResult) {
            this.GetDateIntervalResult = GetDateIntervalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencies", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetCurrenciesRequestBody Body;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(WCF.MNB.GetCurrenciesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrenciesRequestBody {
        
        public GetCurrenciesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetCurrenciesResponseBody Body;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(WCF.MNB.GetCurrenciesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrenciesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrenciesResult;
        
        public GetCurrenciesResponseBody() {
        }
        
        public GetCurrenciesResponseBody(string GetCurrenciesResult) {
            this.GetCurrenciesResult = GetCurrenciesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnits", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetCurrencyUnitsRequestBody Body;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(WCF.MNB.GetCurrencyUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrencyUnitsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string currencyNames;
        
        public GetCurrencyUnitsRequestBody() {
        }
        
        public GetCurrencyUnitsRequestBody(string currencyNames) {
            this.currencyNames = currencyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public WCF.MNB.GetCurrencyUnitsResponseBody Body;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(WCF.MNB.GetCurrencyUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrencyUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrencyUnitsResult;
        
        public GetCurrencyUnitsResponseBody() {
        }
        
        public GetCurrencyUnitsResponseBody(string GetCurrencyUnitsResult) {
            this.GetCurrencyUnitsResult = GetCurrencyUnitsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : WCF.MNB.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<WCF.MNB.MNBArfolyamServiceSoap>, WCF.MNB.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNB.GetInfoResponse WCF.MNB.MNBArfolyamServiceSoap.GetInfo(WCF.MNB.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public string GetInfo() {
            WCF.MNB.GetInfoRequest inValue = new WCF.MNB.GetInfoRequest();
            inValue.Body = new WCF.MNB.GetInfoRequestBody();
            WCF.MNB.GetInfoResponse retVal = ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.Body.GetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNB.GetInfoResponse> WCF.MNB.MNBArfolyamServiceSoap.GetInfoAsync(WCF.MNB.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNB.GetInfoResponse> GetInfoAsync() {
            WCF.MNB.GetInfoRequest inValue = new WCF.MNB.GetInfoRequest();
            inValue.Body = new WCF.MNB.GetInfoRequestBody();
            return ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNB.GetCurrentExchangeRatesResponse WCF.MNB.MNBArfolyamServiceSoap.GetCurrentExchangeRates(WCF.MNB.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public string GetCurrentExchangeRates() {
            WCF.MNB.GetCurrentExchangeRatesRequest inValue = new WCF.MNB.GetCurrentExchangeRatesRequest();
            inValue.Body = new WCF.MNB.GetCurrentExchangeRatesRequestBody();
            WCF.MNB.GetCurrentExchangeRatesResponse retVal = ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.Body.GetCurrentExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNB.GetCurrentExchangeRatesResponse> WCF.MNB.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(WCF.MNB.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNB.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync() {
            WCF.MNB.GetCurrentExchangeRatesRequest inValue = new WCF.MNB.GetCurrentExchangeRatesRequest();
            inValue.Body = new WCF.MNB.GetCurrentExchangeRatesRequestBody();
            return ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNB.GetExchangeRatesResponse WCF.MNB.MNBArfolyamServiceSoap.GetExchangeRates(WCF.MNB.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public string GetExchangeRates(string startDate, string endDate, string currencyNames) {
            WCF.MNB.GetExchangeRatesRequest inValue = new WCF.MNB.GetExchangeRatesRequest();
            inValue.Body = new WCF.MNB.GetExchangeRatesRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.currencyNames = currencyNames;
            WCF.MNB.GetExchangeRatesResponse retVal = ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.Body.GetExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNB.GetExchangeRatesResponse> WCF.MNB.MNBArfolyamServiceSoap.GetExchangeRatesAsync(WCF.MNB.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNB.GetExchangeRatesResponse> GetExchangeRatesAsync(string startDate, string endDate, string currencyNames) {
            WCF.MNB.GetExchangeRatesRequest inValue = new WCF.MNB.GetExchangeRatesRequest();
            inValue.Body = new WCF.MNB.GetExchangeRatesRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.currencyNames = currencyNames;
            return ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNB.GetDateIntervalResponse WCF.MNB.MNBArfolyamServiceSoap.GetDateInterval(WCF.MNB.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public string GetDateInterval() {
            WCF.MNB.GetDateIntervalRequest inValue = new WCF.MNB.GetDateIntervalRequest();
            inValue.Body = new WCF.MNB.GetDateIntervalRequestBody();
            WCF.MNB.GetDateIntervalResponse retVal = ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.Body.GetDateIntervalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNB.GetDateIntervalResponse> WCF.MNB.MNBArfolyamServiceSoap.GetDateIntervalAsync(WCF.MNB.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNB.GetDateIntervalResponse> GetDateIntervalAsync() {
            WCF.MNB.GetDateIntervalRequest inValue = new WCF.MNB.GetDateIntervalRequest();
            inValue.Body = new WCF.MNB.GetDateIntervalRequestBody();
            return ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNB.GetCurrenciesResponse WCF.MNB.MNBArfolyamServiceSoap.GetCurrencies(WCF.MNB.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public string GetCurrencies() {
            WCF.MNB.GetCurrenciesRequest inValue = new WCF.MNB.GetCurrenciesRequest();
            inValue.Body = new WCF.MNB.GetCurrenciesRequestBody();
            WCF.MNB.GetCurrenciesResponse retVal = ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.Body.GetCurrenciesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNB.GetCurrenciesResponse> WCF.MNB.MNBArfolyamServiceSoap.GetCurrenciesAsync(WCF.MNB.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNB.GetCurrenciesResponse> GetCurrenciesAsync() {
            WCF.MNB.GetCurrenciesRequest inValue = new WCF.MNB.GetCurrenciesRequest();
            inValue.Body = new WCF.MNB.GetCurrenciesRequestBody();
            return ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.MNB.GetCurrencyUnitsResponse WCF.MNB.MNBArfolyamServiceSoap.GetCurrencyUnits(WCF.MNB.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public string GetCurrencyUnits(string currencyNames) {
            WCF.MNB.GetCurrencyUnitsRequest inValue = new WCF.MNB.GetCurrencyUnitsRequest();
            inValue.Body = new WCF.MNB.GetCurrencyUnitsRequestBody();
            inValue.Body.currencyNames = currencyNames;
            WCF.MNB.GetCurrencyUnitsResponse retVal = ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.Body.GetCurrencyUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.MNB.GetCurrencyUnitsResponse> WCF.MNB.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(WCF.MNB.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.MNB.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(string currencyNames) {
            WCF.MNB.GetCurrencyUnitsRequest inValue = new WCF.MNB.GetCurrencyUnitsRequest();
            inValue.Body = new WCF.MNB.GetCurrencyUnitsRequestBody();
            inValue.Body.currencyNames = currencyNames;
            return ((WCF.MNB.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
    }
}
